
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LongMetalTableEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {19652, 1, -1, 0}, {19650, 1, 0, 0}, {19651, 1, 1, 0}// 1	2	3	
			, {19653, 0, -1, 0}, {19655, 0, 0, 0}, {19654, 0, 1, 0}// 4	5	6	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LongMetalTableEastAddonDeed();
			}
		}

		[ Constructable ]
		public LongMetalTableEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public LongMetalTableEastAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LongMetalTableEastAddonDeed : BaseAddonDeed
	{
		public override int LabelNumber{ get{ return 1154165; } } //Long Metal Table (East)
		public override BaseAddon Addon
		{
			get
			{
				return new LongMetalTableEastAddon();
			}
		}

		[Constructable]
		public LongMetalTableEastAddonDeed()
		{
			//Name = "Large Metal Table(East)";
		}

		public LongMetalTableEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}